modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/MairwunNx/logblock/issues"

[[mods]]
    modId="logblock"
    version="1.15.2-1.0.0"
    displayName="logblock"
    authors="MairwunNx (Pavel Erokhin)"
    updateJSONURL="https://raw.githubusercontent.com/MairwunNx/logblock/FORGE-1.15.2/update.json"
    displayURL="https://github.com/MairwunNx/logblock"
    description='''
    ...
    '''

[[dependencies.projectessentials]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.projectessentials]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
